# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: perception_image2d.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='perception_image2d.proto',
  package='rs',
  syntax='proto3',
  serialized_pb=_b('\n\x18perception_image2d.proto\x12\x02rs\"p\n\x14PerceptionRawImage2D\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x06\x12\x11\n\tcol_pixel\x18\x02 \x01(\x05\x12\x11\n\trow_pixel\x18\x03 \x01(\x05\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PERCEPTIONRAWIMAGE2D = _descriptor.Descriptor(
  name='PerceptionRawImage2D',
  full_name='rs.PerceptionRawImage2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_ms', full_name='rs.PerceptionRawImage2D.timestamp_ms', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='col_pixel', full_name='rs.PerceptionRawImage2D.col_pixel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='row_pixel', full_name='rs.PerceptionRawImage2D.row_pixel', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='format', full_name='rs.PerceptionRawImage2D.format', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='rs.PerceptionRawImage2D.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['PerceptionRawImage2D'] = _PERCEPTIONRAWIMAGE2D

PerceptionRawImage2D = _reflection.GeneratedProtocolMessageType('PerceptionRawImage2D', (_message.Message,), dict(
  DESCRIPTOR = _PERCEPTIONRAWIMAGE2D,
  __module__ = 'perception_image2d_pb2'
  # @@protoc_insertion_point(class_scope:rs.PerceptionRawImage2D)
  ))
_sym_db.RegisterMessage(PerceptionRawImage2D)


# @@protoc_insertion_point(module_scope)
